### ISSUE TITLE
Duplicate Transaction Hashes

### ISSUE THREAD

**Issue by faberto** [nimiq/core-rs-albatross#1060]
When the validator rewards are paid out it can happen that multiple transactions have the same hash.

#### Requirement?
- Multiple validators that are likely to get assigned the same number of slots in an epoch.
- All these validators need to have the same reward address

#### How does this happen?
Multiple of these validators behave correctly when getting assigned the same number of slots.
They are rewarded the same amount to the same reward address. Now multiple transactions have the same properties and result in the same hash.

#### Sample Data
Block: https://albatross.nimiq.tools/block/63008
Transaction Hash: 7038d48a65a168b3e7a92102ee73c1682b4f49dbb15cb4e150fdfa0a7be0cc3c

**Comment by sisou** [comment]
Since the payouts are for different validators (those can not have the same address), and these transactions are 'simulated' transactions anyway, which are created on-the-fly from the reward inherents, I suggest to write the validator address into the extra data. Then each reward tx is different, even if for the same amount and to the same address.

**Comment by hrxi** [comment]
Fixed by #1976.
