### ISSUE TITLE
RPC: Standard streaming interface

### ISSUE THREAD

**Issue by riptl** [nimiq/core-rs-albatross#126]
The WebSocket mode of the RPC server simply sends JSON blobs on connection.

I suggest we follow standard practice and use an interface similar to Geth's PubSub, which pushes events via JSON-RPC server to client calls.
https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB

This would be in line with the proposed streaming interface on core-js: https://github.com/nimiq/core-js/pull/498

**Comment by jgraef** [comment]
I started a new JSON-RPC implementation over at [nimiq/jsonrpc](https://github.com/nimiq/jsonrpc). This also supports pubsub in form of RPC methods returning `Stream`s. I'm currently working on reworking the RPC methods exposed by the Albatross client.

**Comment by jgraef** [comment]
JSON-RPC over websocket with subscriptions is implemented. At the moment only a few RPC methods are implemented (those that are needed for the testnet). Also documentation is missing. The only "documentation" is the RPC client binary `rpc-client/src/bin/client.rs`.

But since we have everything we need for the testnet, I'll mark this a P-low.

**Comment by styppo** [comment]
Tracking this in #229.
