### ISSUE TITLE
Light client receives macro body, but not justification

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#1411]
As part of #1410 I noticed that in the browser client (which is a light client) **micro** blocks are received as expected as light blocks, i.e. no `body`, but the `justification` is set.

For **macro** blocks however, I noticed the opposite. When received through `client.consensus_proxy().blockchain.read().get_block_at(height, false)`, macro blocks have their `body` set, including RewardTransactions, but the `justification` field is `None`. I believe that should be the opposite?

**Comment by jsdanielh** [comment]
Mmm, for sure the intention was not the opposite since we need macro bodies to get the set of validators and the disabled
slots for blocks verification in the subsequent epoch/batch.
As for the macro block justification, we only use it to verify the block but after that's done we accept the block and since it's final we get rid of the justification. Do you think you will need the justification?

**Comment by sisou** [comment]
Ah, interesting! Like you say it it makes sense.

Let's wait for any feedback from users if they want the justification, before changing anything 👍
