### ISSUE TITLE
The data hashed for `HistoricTransaction` isn't necessarily unique

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#1935]
Likely not an issue in practice, but should be fixed regardless. `HistoricTransaction` delegates hashing to its contained `Transaction` if it's a `HistoricTransaction::Basic`. This might collide with other variants of `HistoricTransaction`.

This is done so that the `HistoricTransaction` corresponding to a known `Transaction` can be looked up easily.

To fix this, I propose to instead hash the hash of the `HistoricTransaction` together with a unique prefix so that you can still look up the `Transaction` by hash, but the hash becomes unique.

CC #1882.

**Comment by viquezclaudio** [comment]
It does happen in practice :)

These two rewards in epoch 2:
`Txn HistoricTransaction { network_id: UnitAlbatross, block_number: 360, block_time: 1635581220000, data: Reward(RewardEvent { validator_address: Address("de9606bf55e452c0961882a12dedc468eaa4152e"), reward_address: Address("e18d595a8d0364703937c1fd9ea67d8a4e64046a"), value: Coin(28000060) }) } at position 31
Txn hash: b135b2daad0f9078fbe76b5d275be82b8b9c7cb142551822117410205db04545

Txn HistoricTransaction { network_id: UnitAlbatross, block_number: 392, block_time: 1635581252000, data: Reward(RewardEvent { validator_address: Address("de9606bf55e452c0961882a12dedc468eaa4152e"), reward_address: Address("e18d595a8d0364703937c1fd9ea67d8a4e64046a"), value: Coin(28000060) }) } at position 63
Txn hash: b135b2daad0f9078fbe76b5d275be82b8b9c7cb142551822117410205db04545`

Have the same hash as this Historic transaction in epoch 1:

`Historic Transaction: HistoricTransaction { network_id: UnitAlbatross, block_number: 328, block_time: 1635581188000, data: Reward(RewardEvent { validator_address: Address("de9606bf55e452c0961882a12dedc468eaa4152e"), reward_address: Address("e18d595a8d0364703937c1fd9ea67d8a4e64046a"), value: Coin(28000060) }) } 
Txn hash: b135b2daad0f9078fbe76b5d275be82b8b9c7cb142551822117410205db04545`


Note that the first two rewards should not have the same hash, since the block height of those rewards should be taken into account for their hash computation

**Comment by sisou** [comment]
The reason might be that for hashing, the reward inherent is hashed as is, without any block information.
https://github.com/nimiq/core-rs-albatross/blob/5e0c54e479b2ca24117e81fd7bad25d95b50be1f/primitives/transaction/src/historic_transaction.rs#L170

https://github.com/nimiq/core-rs-albatross/blob/5e0c54e479b2ca24117e81fd7bad25d95b50be1f/primitives/transaction/src/historic_transaction.rs#L203

Whereas if it would be converted to a transaction first, then hashed, it would be unique as that includes the block number: 
https://github.com/nimiq/core-rs-albatross/blob/5e0c54e479b2ca24117e81fd7bad25d95b50be1f/primitives/transaction/src/historic_transaction.rs#L176-L188

**Comment by hrxi** [comment]
> Whereas if it would be converted to a transaction first, then hashed, it would be unique as that includes the block number:
> 
> https://github.com/nimiq/core-rs-albatross/blob/5e0c54e479b2ca24117e81fd7bad25d95b50be1f/primitives/transaction/src/historic_transaction.rs#L176-L188

That wouldn't be unique in another case: Two distinct elected validators with the same number of slots paying out to the same reward address. Adding the block height to the hashed data should fix it.
