### ISSUE TITLE
Full node - Invalid history root during sync

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2261]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 0.20
- Reproducible in the testnet? (Yes/No): yes
#### Expected behavior
Syncing from an empty database should sync all the way to the head

#### Actual behavior

After the validity window sync has finished, the sync sometimes fails to continue due to a mismatch in the history root.

#### Steps to reproduce

> Configure `client.toml` with a full node
> Sync from with an empty database

#### Crash 
[nimiq-client.log](https://github.com/nimiq/core-rs-albatross/files/14430619/nimiq-client.log)

**Comment by viquezclaudio** [comment]
This is another instance where this was observed with a bit more debug information from the validity sync:
[HistoryMismatch.log](https://github.com/nimiq/core-rs-albatross/files/14435771/HistoryMismatch.log)

The issue is not always reproducible. 

From this log, it is observed that:
`Starting validity window synchronization process verifier_bn=17282264 chunk_index=0 epoch=22 validity_start=17242724 election_in_between=false expected_root=b2fdf1a9b86677b8fa863b8b220991e91835ddfaaa5228035c9843ec7e9370f9`

The macro head is: **17282264**
The history root that we are expecting at the end of the validity window process is:
**b2fdf1a9b86677b8fa863b8b220991e91835ddfaaa5228035c9843ec7e9370f9**

When the validity window syncing is complete, we achieve the desired history root:
`Validity window syncing is complete synced_root=b2fdf1a9b86677b8fa863b8b220991e91835ddfaaa5228035c9843ec7e9370f9`

However, when we try to push the next micro block, it fails:
`Rejecting block block=#17282565:MI:9d65a547f8 block_root=aada111e8cbafeb27c9ef50815cbf880bea3040bdc23cbd9db53763249ff7cd5 history_root=b2fdf1a9b86677b8fa863b8b220991e91835ddfaaa5228035c9843ec7e9370f9 reason="History root doesn't match real history root"`

It is interesting to note that the root that was obtained when pushing the next block is the same as the macro head, i.e:
**b2fdf1a9b86677b8fa863b8b220991e91835ddfaaa5228035c9843ec7e9370f9**

So it seems the history tree was not properly updated when trying to push the next block
