### ISSUE TITLE
Failure to catch up through head requests

### ISSUE THREAD

**Issue by styppo** [nimiq/core-rs-albatross#2745]
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/9929244435/job/27426574778), it was observed that validators 2 and 4 fail to catch up after being restarted. It appears that unknown blocks received from head requests are not being pushed onto the chain, but only after the restart has occurred.

**Comment by Eligioo** [comment]
Similar observation in [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/10024994091)

Seed head: 108
Validator 1 head: 108
Validator 2 head: 105 (was behind due to a restart)
Validator 3 head: 108

Validator 4 after a restart with head 107:
```
2024-07-21T02:54:59.420898083Z DEBUG consensus            | Initiating head requests (to 4 peers)
...
2024-07-21T02:54:59.425463853Z DEBUG consensus            | Trying to establish consensus, checking head request (1 known, 3 unknown)
```

I agree that pushing the `unknown_blocks` is failing. Once a block is gossiped, the node is able to catch up through a `RequestMissingBlocks`.

**Comment by Eligioo** [comment]
One idea I have is that we only accept announcements from synced peers but if we never add peers to the `BlockRequestComponent`/live sync, we will ignore the `unknown_blocks` pushes.
