### ISSUE TITLE
Ignoring blocks in slot after invalid block

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#31]
Our implementation currently differs from the specification in that it ignores invalid blocks, but still accepts further blocks from the same validator during the slot.
According to our specs, it should however ignore any further blocks from this validator during the current slot.

Due to this, in fact, we can immediately start a view change.
*EDIT:* Of course, we should only start a view change, if the invalid block was from the correct block producer for this slot!

**Comment by jgraef** [comment]
Also, like we discussed during launch, we should have a "Proof of Bad Chain" that proofs that a validator extended an invalid chain. This proof would contain the block header from the block in question to the the view changed one. Then we can slash validators that try to extend invalid chains.

Edit: Didn't see there is already an issue about this: #32

**Comment by jgraef** [comment]
If we block the whole validator after a view change, wouldn't that just incentivize having a lot of validator keys? At least one per stake?

With slashing: Here this wouldn't be too much of a problem, since blocking a validator for this epoch, would function as a protection for them. They can't get slashed more than once per epoch. But they would still miss out on all the reward, so slash per block must be higher than the reward they would receive per slot.

Without slashing: The validator would not get any reward and is thus incentivized to have as many BLS keys as possible.

**Comment by paberr** [comment]
Ignoring blocks from the same validator after an invalid block could result in stuck validators.
If a validator sends an invalid block to 1/3+1 of its peers and a valid one to the rest, the 1/3+1 would not accept the valid one anymore, but they also cannot view change.

**Comment by paberr** [comment]
Additional argument against this is: Since blocks are gossiped anyway, invalid ones won't propagate far through the network.
