### ISSUE TITLE
Inconsistent Peer Connections and Consensus Issues Across Devices/Browsers After PoS Migration

### ISSUE THREAD

**Issue by Andjroo111** [nimiq/core-rs-albatross#3116]
Hi Nimiq team,

I've identified inconsistent behavior with the wallet's peer connections and consensus establishment across different devices and browsers.

Current Status by Platform:

Desktop (MacBook):
- Safari: Only connects to 1 peer, can't establish consensus
- Chrome: Successfully connects and establishes consensus
  * Can stake/unstake
  * Transactions not displaying
  * Otherwise functioning normally

Mobile (iPhone):
- Safari: Only connects to 1 peer, can't establish consensus
- Chrome: Same issue as Safari mobile - can't establish consensus beyond 1 peer
- Unable to perform any operations (staking, transactions)

Console Analysis:
When failing, seeing systematic WebSocket connection failures across multiple endpoints:

1. electrum.nimiq.com/electrum failures:
   - Error: "There was a bad response from the server"

2. Seed node connection failures with "Socket is not connected":
   - seed-1.xxx.nimiq.com
   - seed-2.xxx.nimiq.com
   - seed-3.xxx.nimiq.com
   - lumina.seed.nimiq.systems
   - other.seed.nimiq-network.com

Testing Environment:
- Tested across multiple browsers (Safari, Chrome)
- Tested on both desktop and mobile
- Cleared cache/cookies
- Console logs captured via Safari Web Inspector
- Behavior notably different between desktop Chrome and other configurations

**Comment by sisou** [comment]
Apple software should now be able to connect much easier with v1.0.1.

Our working theory of what happened is that in Safari, the networking of a tab or web-worker shares the same thread as the JS environment that is running. Due to missing optimization, in v1.0.0 the Nimiq client was doing a lot of unnecessary work which could suffocate JS's single-threaded environment at 100% for well over 30 seconds. This seems to have hung up the networking of the browser for that context and also lead to timeouts for connections getting exceeded (while the process was blocked by the client).

With v1.0.1 we removed unnecessary work at startup, so the lock on the CPU should now not exceed 15 seconds, and not without breaks, leading to Safari being able to maintain its network connections correctly.
