### ISSUE TITLE
BLS signature sometimes can not be deserialized

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#433]
PR #422 removed a panic when deserialising bls signatures. However where these signatures originate from is unclear. After the change in #422 the client no longer crashes with the panic, the Err cases however do show up occasionally. 

So far the client was not impeded by these signatures, but that does not mean that they can not do so.

In the logs they will show up like this
```
ERROR network | Failed to deserialize message: Invalid value 
 ```
and they occur during macro block production.

Find out where these signatures originate from and why they can not be deserialised.

**Comment by jsdanielh** [comment]
It looks like the problem is that we are failing to tell the network the appropriate type to use for deserialization. Some more details:
In case of `LevelUpdate` messages we have two types:
1. View Changes
2. Tendermint Contributions
They both share the same type ID (121) since that is defined in `hande`l when the `Message` trait is implemented for `LevelUpdateMessage`.

What happens with these messages when they are decoded? The network would use the type ID to figure out which type a message it needs to use for deserialization. But since they both have the same type ID, the network uses the last type passed when calling the network `receive_from_all`. The network does have in place a mechanism that would assert if two receivers are going to be registered for the same type ID but they may not fail if the sender of the message is detected as dropped.
So what I'm seeing in the logs that happens is that for instance:
1. At time `t1`, `peer1` registers a receiver for Tendermint contributions. The registration succeeds as whatever the network had as sender for this type, is classified as stale.
2. At time `t2`, `peer2` serializes a View Change message with `crc1` and sends it to `peer1`.
3. At time `t3`, `peer1` receives the message from `peer2` with `crc1` and tries to decode it as a Tendermint contribution since there doesn't appear to be a call to register a new receiver since `t1` .
4. In `peer1` the message was tried to be decoded as a Tendermint contribution but it was a view change and thus deserialization fails.
