### ISSUE TITLE
Macro blocks chain ordering must be ChainOrdering::Better or ChainOrdering::Extend

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#440]
## Description
Whenever a macro block is pushed the `ChainOrdering` must end up being either `ChainOrdering::Extend` or `ChainOrdering::Better`.

`ChainOrdering::Extend` is the regular case where the macro block exists on the best chain and that is implemented correctly.

`ChainOrdering::Better` is also correctly implemented if the macro block exists on a better chain and the node has to rebranch to the macro block.

Currently a macro block can exist on a `ChainOrdering::Inferior` chain however. In that case the chain ordering should be changed to `ChainOrdering::Better` such that a rebranch to the inferior chain that contains the macro block is done. Chains with a macro block are considered the best chain of a batch by definition.

## Example:
The chain is at block `n.0` with `v = 3f+1` Validators. The block at height `n+2` is a macro block.
`bn.vn` denotes a block with block number `bn` and view number `vn`.

* no block `n+1.0` is received thus a view change is started on Validators in Set `A` with `|A| = 2f+1` .
* after that before the view change to `n+1.1` is completed the block `n+1.0` is received by Validators in Set `B` with `|B| = 2f+1` Validators
  * `A` and `B` are not equal and cannot be disjoint.
* Validators `B` now produce `n+2.0` which is the macro block in this example. They can succeed in doing so as the `2f+1` required votes are present. They produce, vote on successfully and push the block `n+2.0`.
* The view change completes for a Validator in `A` but not `B` who is for the example also the block producer of `n+1.1`. The view change can complete as the required `2f+1` votes have been send by `A`. It produces and pushes the block `n+1.1`.
  * This validator can now receive both `n+1.0` and `n+2.0` but will order them both on a `ChainOrdering::Inferior` as `n+1.1` exists.
  * The validators in `B` can now receive the Block `n+1.1` but will ignore it since the batch this block is in was finalised by `n+2.0`.
  
The behaviour of the Validator on `n+1.1` must be changed such that it can rebranch to `n+2.0` if that is a macro block.

Note that #439 is a requirement for this Issue as otherwise `n+2.0` will be rejected as an orphaned block even before ordering the chains by the validator who produced `n+1.1`.

**Comment by brunoffranca** [comment]
The situation you're describing is not possible as per the protocol.
Assuming `v = 3f+1` with `f` malicious validators. The view change at block `n+1` happens with `2f+1` votes from the validator set `A`. Assume `f` votes are from malicious validators (this is the worst case), that leaves `f+1` honest votes. That leaves only `f` validators who didn't participate in the view change (all of them honest).
When `n+1.0` is broadcast there are only `f` validators that can be on that chain, the ones that didn't participate in the view change. The other `f+1` honest validators are on the `n+1.1` chain and will remain so. The `f` malicious validators do their own thing.
Now, there are not enough votes to produce `n+2.0`. There are at most `2f` votes, the `f` honest validators that didn't view changed and the `f` malicious validators. The `f+1` honest validators that did view changed are on a better chain and will not vote for `n+2.0`. No blocks (or view changes) will be produced until the `f` honest validators upgrade to the better chain.
Macro blocks cannot turn an inferior chain into a superior chain, it only appears so. It is not that a macro block decides what chain is better, it is that we are guaranteed that a macro block is on the better chain because `2f+1` validators had to reach a consensus on which chain to build on. **But a macro block proposal should only be valid if it is building on a superior chain.**

**Comment by nibhar** [comment]
The requirement of #439 can (and because of @brunoffranca 's comment in that issue should) be removed by providing a more specialised way of pushing inferior chains as long as they contain the macro block for that batch.

I.e
```
impl Blockchain {
  fn push_finalised_chain(
    this: RwLockUpgradableReadGuard<Self>,
    blocks: Vec<Block>,
  ) -> Result<PushResult, PushError> {
    assert!(blocks.last().expect("blocks must not be empty").is_macro());
    ...
  }
}
```

`blocks` could be provided by a missing blocks request.
