### ISSUE TITLE
Don't re-verify transactions from blocks that were already verified in mempool

### ISSUE THREAD

**Issue by fiaxh** [nimiq/core-rs-albatross#478]

**Comment by brunoffranca** [comment]
Turns out there is no simple way to do this. The consensus crate doesn't have a mempool reference or any notion of it. In fact, only validators have a mempool. And new blocks (not produced by us) are received and pushed from the consensus crate. Blocks that are produced by us are pushed from the validator crate, but then we could just skip all transaction verification.
Also, since only validators have mempools, this feature might not be that important.

**Comment by brunoffranca** [comment]
I stand corrected. The Rust-Fu is strong in you, @styppo.
