### ISSUE TITLE
Macro Block PBFT

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#54]
As explained in #53 and #49, there are still some implementation issues around the Macro Block PBFT.
I discussed these with @jgraef and Bruno Franca just now and here's the list of things that still need to be changed:

1. The timeout for view changes should stop when receiving a valid proposal. Even if the network is split at that moment and half of the validators start a view change, they won't be able to complete it and can thus accept the valid proposal after a reunion of the network.
2. A validator could provide two valid, but different proposals. The way to resolve this is to define a strict ordering on proposals (e.g., by their hash) and require honest validators to always choose the lowest.
3. Considering case 2. and a split network, it can happen that half of the validators sends `prepare` for proposal A and the other half for B. So, after a reunion of the network, validators have to be allowed to send another `prepare` for the lower block (e.g., A). But under no circumstances, they will ever send `commit` messages for both blocks. This last requirement is actually already enforced by the rule to only send `commit` if you have 2f+1 prepares.

**Comment by styppo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix MacroBlock PBFT](https://trello.com/c/Gwv50bFs/5-fix-macroblock-pbft)

**Comment by jgraef** [comment]
Currently a validator doesn't verify the extrinsics hash in the proposal. I think this was fine, because a macro block with invalid extrinsics wasn't accepted, but view-changed, even after everyone committed to it. Since we only want commits on one block, we need to check that. So when receiving a pBFT proposal, we need to compute the extrinsics and check that the hash in the proposal is correct. We can then also store the extrinsics to get the full block once the proposal is accepted.

**Comment by paberr** [comment]
While reviewing the PR #99, I thought a bit about the following scenario:
- A block is published and 2/3 of the validators send a prepare for this block.
- At this point, the block producer publishes a new block with a lower hash to only a subset of the validators that also sent prepare for the previous block.
- Validators that did not receive the new block will commit on the first block.

What will happen now? The validators who committed on the first block will not be able to commit on the second with the lower hash.
But the rest of the validators also won't be able to finish the second block's PBFT.

**Comment by brunoffranca** [comment]
Analyzing the rules, we know that:

1. Validators never send two commit messages in the same block height and view number.
2. Whenever validators receive 2f+1 prepare messages, they send a commit message.

In the above scenario, even though some of the validators receive a better (lower hash) proposal, they will also receive 2f+1 prepare messages for the first proposal. What will happen is that those validators will send a commit message to the first proposal, even if they already sent a prepare message to the second proposal.

There's nothing in the rules that says that a validator can't send a commit message to a proposal if he already sent a prepare message to another message. Given that, in the above scenario, the new better proposal will never get 2f+1 prepare messages, it will never get a single commit message, so the first proposal will be finalized.

**Comment by brunoffranca** [comment]
Having said that, I realize that the whitepaper has no information on the view change protocol for the macro blocks (it's only given for the micro blocks). Also, what we want is to be confident that there's not some contrived scenario where the network halts because of some timing issue.
So, I'll do some research and post the view change protocol for PBFT here (ideally today).
