### ISSUE TITLE
Flaky `it_can_aggregate` test

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#830]
Seen in a couple of CI runs, e.g. https://github.com/nimiq/core-rs-albatross/runs/6368215247?check_suite_focus=true, https://github.com/nimiq/core-rs-albatross/runs/6368135617?check_suite_focus=true or https://github.com/nimiq/core-rs-albatross/runs/6366864317?check_suite_focus=true.
```
thread 'it_can_aggregate' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `8`: Not all contributions are present', handel/tests/mod.rs:430:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    it_can_aggregate
```

**Comment by nibhar** [comment]
This should hopefully be fixed by https://github.com/nimiq/core-rs-albatross/commit/30f1d780dc41ea7b9f4bf21b77e9216c979558c5

**Comment by hrxi** [comment]
That's an… interesting fix. :P

**Comment by nibhar** [comment]
The second part of that test verifies that once an aggregation is completed it will respond with a fast tracked full aggregation to any update send by another peer. For that to work the aggregation must finish first. Since all of the aggregation tasks are spawned i am unaware of influencing their execution schedule. 

There is another way of doing this without the sleep to let the spawned tasks conclude the aggregation. For now this should work fine, but I am likely going to revisit that test soon anyways.
