### ISSUE TITLE
[RPC][request] Improved / extended websocket functionality

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#861]
Hi team,

Since beta community developers are now able to request access to the albatross RPC interface to provide feedback, I thought it was time to start an issue with some feature requests regarding the RPC inteface of my own. 

## 1. Improved websocket `headSubscribe` functionality
The RPC inteface supports a specific RPC method over websockets `headSubscribe` which pushes the block hash of new blocks that have been validated / added to the blockchain. This feature provides some first hooks to receive active updates from the blockchain, but is still rather limited in my opinion. 

### Problem 
Currently the `headSubscribe` method pushes block hashes to the client. It is still required for the client to retrieve the entire block via`getBlockByHash` in order to discern what type of block has been added to the blockchain and make a decision on whether to do something with it or not. The current implementation has the effect of creating a push pull mechanism where the client is still pulling all blocks, which in my view moves potential efficiency gains of events pushed to the client away.

I foresee applications that may be interested in only specific blocks, for example only macro blocks or only blocks with transactions or only an election block, but in order to filter these we have to still request all blocks from the node to filter the blocks we are interested in.

### Possible solutions 
1. One way to already have some more idea from a client side perspective if you are interested in a block would be to receive more information than only the hash. This could include the block hash, the block number, the block type and in case of a macro block if it is a checkpoint block or election block. This would give applications options to implement event driven design, without having to pull data for all blocks received which would make implementations more efficient. 
2. Another option would be to push the entire block that you would also receive from responses like `getBlockByHash`. Including transactions or only transaction hashes could be a parameter that is also used for `getLatestBlock`, `getBlockByHash` and `getBlockByNumber`

## 2. websocket events for validator and or staker during election block 
This request relates to adding functionality to the websocket RPC interface to receive events / updates related to the staking contract, especially or maybe evenly exclusively when an election block begins. 

### Problem 
One of the major challenges for pools in particular is to keep track of the staking contract. The staking contract always receives transactions and only has a solidified state during the last micro block of an epoch and during the election block. Before and after these blocks, the staking contract can change. It is therefore important for pools to check in this small window of two blocks to check if a validator is elected for a new epoch and receive the list of delegated stakers. Currently the only way to do this is to keep track of the blockheight and make sure to request the data within the limited time window. 

### Solution 
It would be a great addition if the response of `getValidatorByAddress` could be received as websocket event when the last micro block of an epoch passes or when an election block begins. For other applications it might be an added benefit to have similar websocket events for `getStakerByAdress` but I deem the validator information to be more crucial. 

## 3. return the blockheight in the response of `getValidatorByAddress` 
In addition to request number 2, it would be great if the blockheight can be returned in the response of `getValidatorByAddress`. As explained above the window to retrieve staking contract information for a new epoch is limited. Having a block height in the response indicating the block at when the staking contract information was obtained provides extra indicators to the client if the information was obtained in the correct window. 

I gladly hear your thoughts on these requests. Of course other community members and developers are welcome to join the discussion and share their thoughts as well. 

Best regards,
~Redmaner

**Comment by styppo** [comment]
Hi redmaner,

thanks a lot for the detailed feature request.

1. The current mechanism wasn't built for the short block times that we have now and is indeed pretty inefficient. I like your solution to send (full) blocks instead of only the block hash in a similar fashion to `getBlockByHash`, potentially with some finer-grained control over which blocks and what data (transactions, additional fields) to return.

2. It's a good idea to introduce a new websocket event stream that emits staking contract events for a specific set of validators. I don't see an issue with emitting an event before an election block that includes the response of `getValidatorByAddress` as long as we don't include all stakers, as this could get expensive. To track individual stakers, it's probably more efficient to emit "live" (i.e. during the epoch) update events whenever the stakers change for a particular validator. This would make it necessary to maintain a live copy of the stakers in the external client, but make it potentially easier to re-sync the stakers via `getValidatorByAddress(includeStakers = true)` if some events are missed.

3. This makes sense, not only for this specific request, but for all requests that compute their response from the current head state. We should also return the block hash to avoid ambiguities.  

Cheers,
styppo

**Comment by Admiiminsupport** [comment]
Kindly open this live chat to talk to the customer service directly on any of of your issues 

https://direct.lc.chat/14201763/

**Comment by redmaner** [comment]
With the changes from @ii-cruz being merged, this can be closed. Thanks a lot!
