### ISSUE TITLE
Include `BlockchainState` in RPC responses where applicable

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#970]
As was discussed in #861 RPC requests whose returned values depend on the head state of the blockchain should include the head block number and head hash the value was queried at. This provides context to the validity of those values as they change with the head changing.

Currently `BlockchainState<T>` fulfils this purpose for a select number of requests. 

Other RPC calls whose return values depend on the head state do not include these values yet.

Further discussion about the `BlockchainState<T>` can also be found in #963. The discussion is out of scope for that PR, thus this Issue is supposed to progress that conversation and also to track which RPC calls to modify.

**Comment by Eligioo** [comment]
To continue the discussion here I went through the different `dispatchers` currently implemented and came up with a few points as a first attempt to reach an agreement on which RPC methods return type should be wrapped inside a `BlockchainState`.

My first take on this is that I think it's not necessary for other `dispatchers` other than the `BlockchainDispatcher` to have results wrapped inside a `BlockchainState`. Due to the fact that none of the other methods have to rely on the head state of the blockchain. This will exclude `Consensus`, `Mempool`, `Network`, `Policy`, `Validator`, and `Wallet`.

By only focusing on the `BlockchainDispatcher` I've come up with the following table where it might be good to wrap the result into a `BlockchainState`. This list is meant as a proposal and feedback is appreciated.

| Method | Should be wrapped |
|---|---|
| get_block_number | No |
| get_batch_number | No |
| get_epoch_number | No |
| get_block_by_hash | No |
| get_block_by_number | No |
| get_latest_block | No |
| get_slot_at | Yes |
| get_transaction_by_hash | No |
| get_transactions_by_block_number | No |
| get_inherents_by_block_number | No |
| get_transactions_by_batch_number | No |
| get_inherents_by_batch_number | No |
| get_transaction_hashes_by_address | No |
| get_transactions_by_address | No |
| get_account_by_address | Yes |
| get_active_validators | Yes |
| get_current_slashed_slots | Yes |
| get_previous_slashed_slots | Yes |
| get_parked_validators | Yes |
| get_validator_by_address | Yes |
| get_staker_by_address | Yes |
| subscribe_for_head_block | No |
| subscribe_for_head_block_hash | No |
| subscribe_for_validator_election_by_address | Yes |
| subscribe_for_logs_by_addresses_and_types | Yes |

**Comment by nibhar** [comment]
Aside from what requests need this information another question is how to structure those responses.

Currently the actual response to the request is flattened into the `BlockchainState`. Ignoring the fact flattening the response does not work for collections like `Vec<_>`, my personal feeling is that mixing these together is somewhat irritating. When returning i.e a `Validator` object, it now also contains a `block_number` and a `block_hash` without any notion what they mean, in particular what they have to do with the validator in question. 

I would rather have these two sets of data separated from one another. Some options include:
* Just not flattening them is one option, which I would see the reference block more like a header of sorts for that response. I would argue that a benefit of it would be that the reference is immediately obvious for every request that depends on the head state. 
* Putting the reference block in a separate field in the response is another option separating the two. It is arguably nicer to have the response be on the root level of the response, with the additional information contained within. One more benefit to this is that for each response accessing the data works exactly the same. This requires a non generic approach to responses which depend on the head state of the chain. Potentially also duplicated data for collections.
* Keeping the flattened response is another option. For collections a miscellaneous type which can be flattened can be created. That however opens up 3 different ways of delivering the data. Directly, directly including additional `block_number` and `block_hash` fields and one level down for collections with the reference block fields remaining in the root level.

This is obviously an incomplete list and I am also biased so this is really only meant to further the discussion on the topic.
Opinions and discussion here is appreciated, in particular from those using the RPC.

**Comment by redmaner** [comment]
@nibhar I agree to at least separate blockchain state data, since having flattened fields `block_number` and `block_hash` can be rather confusing without the proper context. 

I work a lot with third party API's at work, and a common pattern I see is that the main data object or array of objects that is being returned is wrapped in a `data` field, where other metadata related fields like metadata or pagination are added as separate keys in the root message. Something similar can be employed here as well. For example for `Validator`:
```
{
  "data": {
    "address": " NQ04 XEHA A84N FXQ4 DPPE 82PG QS63 TH1X XCHQ",
    "balance": 100000000
    ...
  },
  "reference_block": {
    "block_number": 128,
    "block_hash": "b1f73431cdeaf227e5bcca968192eece025de855a4d2be561a5af88be8a8903d"
  }
}
```

The next best option is to return the main data in the root of the message like it is now, but return the blockchain state in a separate field. But to be honest I'm more in favor of clear separation, and have the main objects wrapped as well.

**Comment by sisou** [comment]
I agree with @redmaner. Having it consistent is better than having it differently for objects and arrays. I can get on board with the `data` and `meta` (or however named) top-level fields.

**Comment by ii-cruz** [comment]
As of now, it seems we have converged on the option of having both `data` and the `meta` top-level fields for the RPC methods listed above.

We should also discuss the coherency with other RPC methods that don't require the metadata field. When making the changes we could leave those methods without those higher-level fields as they are currently implemented, however that leads to a non-standardized interaction. I am a bit more inclined to introducing the `data` field on every method's response, thus standardizing the access to the data of a response provided by the RPC. 

Could you share your thoughts on this?

**Comment by redmaner** [comment]
@ii-cruz I don't have a strong preference. I think having some consistency across the entire RPC interface makes sense. Since introducing the `data` mapping already brings breaking changes, might as well break everything now to be more ready for future developments.
